# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f04c90cd0f69f39622dbf56afeb56fdfa273830f750ca70c51e2298d2ed4e971d5d50d14bb09a96a7dd1de980c205cb846e20275edab9b3f083307deb6f130a

test:
  secret_key_base: 508088da711fbb4486d4f11bd49b52158fe3a20020a88efa58e7c64607405c99247fed185c1b1addc7b265811ad9a08c6141be59e89d000b5678b9e97acd2876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
